# Generated by Django 3.0.2 on 2020-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201125_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=200)),
                ('bands', models.CharField(choices=[('Personal Allowance', 'Personal Allowance'), ('Basic Rate', 'Basic Rate'), ('Higher Rate', 'Higher Rate'), ('Additional Rate', 'Additional Rate')], default='Basic Rate', max_length=200)),
            ],
        ),
    ]
